### ISSUE TITLE
Refreshing Sprites

### ISSUE THREAD

**Issue by bencoveney** [nikkorn/IS#27]
Yo @nikkorn (and martin - if you see this)

Figured I would make an issue to ask your input before I start putting sprites in.

For a start I have been using only the colors from [the sprite-sheet](https://opengameart.org/content/tiny-16-basic) where you have grabbed sprites from already.

![palette](https://user-images.githubusercontent.com/1053494/27494395-9851729a-5845-11e7-8631-d93eaa3ee545.png)

I have generated a load of 16x16 sprites. They are all in one image at the moment which is what we want I assume? It is the standard to bundle them into a sprite-sheet for efficiency reasons but also i find it easier to edit. What do you think?

![tiles](https://user-images.githubusercontent.com/1053494/27494462-e6e47b78-5845-11e7-872f-6cf513c18963.png)

The other thing I have in that image is 2 different "weapon chests" with a sword in them. One takes up 2x3 tiles and one takes up 1 tile. If we have each thing in the shop taking up only 1 tile I think it will be pretty hard for anyone to see the items for sale, and the sprite will be limited to "its a sword" rather than "its a scimitar with a blue handle and ruby embedded in the hilt". What do you reckon?

Below are 2 different perspectives where I have compiled the sprites into a rough shop. Let me know what your opinions are. I obviously spent more time on **A** than **B** but the **B** could be spiced up to look just as good.

Perspective A
![composite1](https://user-images.githubusercontent.com/1053494/27494613-9837c2ae-5846-11e7-953c-db87f25e58c7.png)

Perspective B
![composite2](https://user-images.githubusercontent.com/1053494/27494617-9b5dfde0-5846-11e7-827d-9533a82f4618.png)

One thing I will suggest is maybe we could think about changing the two different states from "World and Town" to "World (including town) and Shop"? I think this could work for a couple of reasons:

- It might allow us to have a larger scale shop with really a detailed interior and items without needing to extend that detail to the town
- It could allow us to use a different perspective for the shop (e.g. Perspective A to show off the items, furniture) and the rest of the world (Perspective B to show of the cities, geography).
- The main thing the game is about is running a shop. I think it makes sense for there to be one screen where the shop is the main focus, rather than it being one small section of one of the screens.

The pictures on [LPC Inside](https://opengameart.org/content/lpc-city-inside) are kinda along the lines of what I am thinking, except scaled up a bit.

**Comment by nikkorn** [comment]
I love the sprites they are so good! In regards to perspective I like A as it adds another dimension and more potential for detail. Will have to think about the item display tile size it's a good point. Also I super agree with having an independent state for the shop for the reasons you mention as well as making it easier to differentiate between rules which need to be inforced within the shop as well as everywhere else; like I would expect npcs to have behaviour specific to the shop only.

**Comment by bencoveney** [comment]
Sweet 👯 Probably won't be working on the game this weekend but can talk on Monday.

![](http://i.imgur.com/q7XSItd.jpg)
