### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by bencoveney** [nikkorn/IS#42]
Would like to change the folder structure a bit. What do you guys think of:

- Removing "com.itemshop" prefix from packages? (Understand its a common thing but gives us 0 benefit and annoying folder nesting)

- Move some "sub-"packages to be folders e.g:

```
factories
factories.characters
factories.items
factories.tiles

factories
  /characters
  /items
  /tiles
```

**Comment by nikkorn** [comment]
Sounds good to me :)

**Comment by bencoveney** [comment]
Disregard this i misunderstood what it meant when i saw [folders](https://stackoverflow.com/questions/23581175/eclipse-source-folders-vs-packages) in the menu.
